### ISSUE TITLE
License notices and binaries in /lib

### ISSUE THREAD

**Issue by donaldr3** [altuncu/BlockSignal#1]
It seems that the project is lacking proper license notices. License notices at the top of source files let users know whether they may use the work under the current license or any later version. You can learn how to use GNU licenses at <https://www.gnu.org/licenses/gpl-howto.en.html>. There also seem to be some binary files in the lib folder. What are these and where is the source for them? Thank you.

**Comment by altuncu** [comment]
Thank you for noticing. I added the missing licence notices and removed the unnecessary library containing some binary files in libs folder. I hope it is OK now, so I'm closing the issue.
